# Generated by Django 3.2.3 on 2021-05-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('it', 'Italian')], default='ru', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='/', max_length=512, unique=True),
        ),
    ]
