# Generated by Django 3.2.3 on 2021-05-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='/', max_length=512),
        ),
    ]
