# Generated by Django 3.2.3 on 2021-06-05 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_start_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_game',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время начала партии'),
        ),
    ]
