# Generated by Django 3.2.4 on 2021-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_start_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Партия', 'verbose_name_plural': 'Партии'},
        ),
        migrations.AlterField(
            model_name='game',
            name='chess_variant',
            field=models.CharField(choices=[(1, 'Инь-Ян'), (2, 'Фланговая'), (3, 'Инь-ян / Фланговая'), (4, 'Инь-ян / Фибоначчи'), (15, 'Классические'), (16, 'Фишера')], default=1, max_length=1, verbose_name='Шахматный вариант'),
        ),
    ]
